'use client';
import { useEffect, useState } from 'react';
import PageHeader from '@/components/PageHeader';
import Card from '@/components/Card';
import BigButton from '@/components/BigButton';
import Icon from '@/components/Icon';
import { callAi, getAiSettings, requestAiSetup } from '@/lib/aiClient';
import { cachedRecipe, cacheRecipe, getRecipe } from '@/lib/recipes';

export default function RecipeDetails(){
 const[id,setId]=useState('');const[backHref,setBackHref]=useState('/meal-ideas');const[recipe,setRecipe]=useState(null);const[analysis,setAnalysis]=useState(null);const[loading,setLoading]=useState(true);const[analyzing,setAnalyzing]=useState(false);const[error,setError]=useState('');
 useEffect(()=>{const params=new URLSearchParams(window.location.search),recipeId=params.get('id')||'';setBackHref(params.get('from')==='saved'?'/meal-ideas/saved':'/meal-ideas');setId(recipeId);if(!recipeId){setError('No recipe was selected.');setLoading(false);return}const cached=cachedRecipe(recipeId);if(cached){setRecipe(cached);if(cached.generatedByAi)setAnalysis({overview:cached.overview,nutrition:[cached.protein,cached.calories].filter(Boolean).join(' · ')||'Nutrition values were not estimated.',suitableFor:'Use the ingredients and portions to decide whether this recipe fits your preferences and dietary needs.',difficulty:cached.difficulty,flavor:'Flavor depends on the listed ingredients and seasoning.',tips:[],substitutions:[],storage:'Store leftovers promptly in a covered container and use normal food-safety guidance.',tags:cached.tags||[],sources:[]});setLoading(false)}else getRecipe(recipeId).then(result=>{if(!result)throw new Error('This recipe could not be found.');cacheRecipe(result);setRecipe(result)}).catch(reason=>setError(reason.message)).finally(()=>setLoading(false));try{const saved=JSON.parse(sessionStorage.getItem(`wc-recipe-analysis-${recipeId}`)||'null');if(saved)setAnalysis(saved)}catch{}},[]);
 async function analyze(target=recipe){if(!target||analyzing)return;const settings=getAiSettings();if(!settings.profile||!settings.consent||!settings.config?.apiKey){requestAiSetup();return}setAnalyzing(true);setError('');try{const result=await callAi({mode:'recipe-analysis',recipe:target,profile:settings.profile});setAnalysis(result);sessionStorage.setItem(`wc-recipe-analysis-${target.id}`,JSON.stringify(result))}catch(reason){setError(reason.message)}finally{setAnalyzing(false)}}
 if(loading)return <div className="px-5 pb-5"><PageHeader title="Recipe" backHref={backHref}/><Card className="mt-4"><div className="flex items-center gap-3"><span className="spinner h-7 w-7 rounded-full border-2 border-teal-light border-t-teal"/><p className="font-bold">Loading recipe…</p></div></Card></div>;
 if(!recipe)return <div className="px-5 pb-5"><PageHeader title="Recipe" backHref={backHref}/><Card className="mt-4"><p className="font-bold">Recipe unavailable</p><p className="mt-2 text-sm text-inkSoft">{error}</p></Card></div>;
 const tags=analysis?.tags?.length?analysis.tags:recipe.tags;
 return <div className="px-5 pb-5"><PageHeader title="Recipe details" backHref={backHref}/>
  <div className="scanner-enter -mx-5 -mt-1">{recipe.image?<img src={recipe.image} alt={recipe.title} className="aspect-[4/3] max-h-[420px] w-full bg-canvas object-cover"/>:<div className="flex aspect-[4/3] max-h-[360px] w-full items-center justify-center bg-gold-light text-gold"><Icon name="bowl" size={72}/></div>}</div>
  <div className="relative -mt-6 rounded-t-[28px] bg-canvas px-0 pt-6"><p className="eyebrow">{recipe.category}{recipe.area?` · ${recipe.area}`:''}</p><h1 className="mt-1 font-display text-3xl font-bold">{recipe.title}</h1><div className="mt-3 flex flex-wrap gap-2">{tags.map(tag=><span key={tag} className="inline-flex min-h-touch items-center rounded-full bg-teal-light px-3 text-sm font-bold text-teal-dark">{tag}</span>)}</div>
   <div className="mt-5 grid grid-cols-2 gap-3"><Card className="p-3"><p className="text-sm text-inkSoft">Difficulty</p><p className="mt-1 font-bold">{analysis?.difficulty||'Not analyzed'}</p></Card><Card className="p-3"><p className="text-sm text-inkSoft">Servings</p><p className="mt-1 font-bold">{recipe.servings||'Not provided'}</p></Card><Card className="p-3"><p className="text-sm text-inkSoft">Preparation</p><p className="mt-1 font-bold">{recipe.prepTime||'Not provided'}</p></Card><Card className="p-3"><p className="text-sm text-inkSoft">Cooking</p><p className="mt-1 font-bold">{recipe.cookTime||'Not provided'}</p></Card><Card className="p-3"><p className="text-sm text-inkSoft">Total time</p><p className="mt-1 font-bold">{recipe.totalTime||'Not provided'}</p></Card><Card className="p-3"><p className="text-sm text-inkSoft">Calories</p><p className="mt-1 font-bold">{recipe.calories||'Not provided'}</p></Card></div>
   {analyzing&&<Card className="mt-4 bg-teal-light"><div className="flex items-center gap-3"><span className="spinner h-7 w-7 rounded-full border-2 border-white border-t-teal"/><div><p className="font-bold">Preparing your cooking summary</p><p className="mt-1 text-sm text-inkSoft">Reviewing the ingredients and cooking steps…</p></div></div></Card>}
   {!analysis&&!analyzing&&<Card className="mt-4"><h2 className="font-display text-xl font-bold">Optional AI cooking overview</h2><p className="mt-2 text-sm leading-relaxed text-inkSoft">Generate a concise nutrition, flavor, and technique summary only when you need it. Opening a recipe uses no AI tokens.</p><BigButton className="mt-4" onClick={()=>analyze()}>Generate overview</BigButton></Card>}
   {analysis&&<Card className="mt-4 bg-teal-light"><div className="flex gap-3"><Icon name="sparkle" className="shrink-0 text-teal-dark"/><div><h2 className="font-display text-xl font-bold">Cooking overview</h2><p className="mt-2 text-sm leading-relaxed text-ink">{analysis.overview}</p><p className="mt-3 text-sm leading-relaxed text-inkSoft"><strong className="text-ink">Nutrition:</strong> {analysis.nutrition}</p><p className="mt-2 text-sm leading-relaxed text-inkSoft"><strong className="text-ink">Suitable for:</strong> {analysis.suitableFor}</p><p className="mt-2 text-sm leading-relaxed text-inkSoft"><strong className="text-ink">Flavor:</strong> {analysis.flavor}</p></div></div></Card>}
   <details open className="mt-4 rounded-2xl border border-line bg-surface p-4"><summary className="cursor-pointer font-display text-xl font-bold text-ink">Ingredients ({recipe.ingredients.length})</summary><ul className="mt-4 space-y-3">{recipe.ingredients.map((item,index)=><li key={index} className="flex gap-3 border-b border-line pb-3 last:border-0"><span className="font-bold text-teal-dark">{item.measure||'As needed'}</span><span>{item.name}</span></li>)}</ul></details>
   <details className="mt-4 rounded-2xl border border-line bg-surface p-4"><summary className="cursor-pointer font-display text-xl font-bold text-ink">Cooking instructions ({recipe.instructions.length})</summary><ol className="mt-4 space-y-4">{recipe.instructions.map((step,index)=><li key={index} className="flex gap-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-teal text-sm font-bold text-white">{index+1}</span><p className="pt-1 text-sm leading-relaxed">{step}</p></li>)}</ol></details>
   {analysis?.tips?.length>0&&<details className="mt-4 rounded-2xl border border-line bg-surface p-4"><summary className="cursor-pointer font-display text-xl font-bold">Helpful cooking notes</summary><ul className="mt-4 space-y-3">{analysis.tips.map((tip,index)=><li key={index} className="flex gap-2 text-sm leading-relaxed"><Icon name="check" size={18} className="mt-1 shrink-0 text-teal-dark"/>{tip}</li>)}</ul>{analysis.substitutions?.length>0&&<><h3 className="mt-5 font-bold">Substitutions</h3><ul className="mt-2 space-y-2">{analysis.substitutions.map((item,index)=><li key={index} className="text-sm leading-relaxed text-inkSoft">{item}</li>)}</ul></>}</details>}
   {analysis?.storage&&<Card className="mt-4"><h2 className="font-display text-xl font-bold">Storage</h2><p className="mt-2 text-sm leading-relaxed text-inkSoft">{analysis.storage}</p></Card>}
   <Card className="mt-4"><h2 className="font-display text-xl font-bold">Sources</h2>{recipe.sourceUrl?<a href={recipe.sourceUrl} target="_blank" rel="noreferrer" className="mt-3 flex min-h-touch items-center justify-between rounded-xl bg-canvas px-3 font-bold text-teal-dark">Original recipe <Icon name="chevron" size={19}/></a>:<p className="mt-2 text-sm text-inkSoft">No original source link was supplied by the recipe record.</p>}{analysis?.sources?.length>0&&<details className="mt-3"><summary className="cursor-pointer text-sm font-bold text-teal-dark">Additional references ({analysis.sources.length})</summary><div className="mt-2 space-y-2">{analysis.sources.map((source,index)=><a key={index} href={source.uri} target="_blank" rel="noreferrer" className="block rounded-xl bg-canvas p-3 text-sm font-bold text-teal-dark">{source.title||`Reference ${index+1}`}</a>)}</div></details>}</Card>
   {error&&<p role="alert" className="mt-4 rounded-2xl bg-clay-light p-4 text-sm text-clay">{error}</p>}
  </div>
 </div>
}
