'use client';
import { useEffect, useMemo, useState } from 'react';
import PageHeader from '@/components/PageHeader';
import Card from '@/components/Card';
import Icon from '@/components/Icon';
import useStoredState from '@/components/useStoredState';
import { aggregateMonthly, buildBiomarkerTrends, ensureScanIdentity } from '@/lib/bloodTrends';

const demoDates=new Set(['2026-07-21','2026-06-18','2026-05-16']);
const explanations={
 hemoglobin:'A protein in red blood cells that carries oxygen.',
 'white-blood-cells':'Cells involved in the body’s immune response.',
 'red-blood-cells':'Cells that carry oxygen through the body.',
 platelets:'Blood components involved in clotting.',
 hematocrit:'The proportion of blood made up of red blood cells.',
 glucose:'The amount of sugar measured in the blood.',
 creatinine:'A waste product commonly measured in kidney-related testing.',
 sodium:'An electrolyte involved in fluid balance and nerve function.',
 potassium:'An electrolyte involved in muscle, nerve, and heart function.',
};
function isOldDemo(row){return !row.source&&demoDates.has(row.date)&&row.labs?.length===2&&row.labs.some(lab=>lab.name==='Hemoglobin')&&row.labs.some(lab=>lab.name==='White blood cells')}
function readableDate(date){return date?new Date(`${date}T12:00`).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'Not available'}
function readableStatus(status){return({ 'within-provided-range':'Within printed range','below-provided-range':'Below printed range','above-provided-range':'Above printed range','range-unavailable':'No range provided','range-unparseable':'Range could not be read','missing-value':'Value could not be read'}[status]||'Status unavailable')}
function statusTone(status){return status==='within-provided-range'?'bg-teal-light text-teal-dark':status==='below-provided-range'||status==='above-provided-range'?'bg-clay-light text-clay':'bg-gold-light text-ink'}
function changeText(trend){if(trend.comparisonStatus!=='comparable')return({ 'unit-mismatch':'Previous result uses a different unit','missing-unit':'A unit is needed for comparison','missing-value':'A numeric value is needed','not-enough-history':'No earlier compatible result'}[trend.comparisonStatus]||'Not comparable');const value=trend.change.absolute;return`${trend.change.direction[0].toUpperCase()+trend.change.direction.slice(1)} ${trend.change.direction==='stable'?'':`by ${Math.abs(Number(value.toFixed(2)))} ${trend.latest.unit}`}`.trim()}

export default function BloodWork(){
 const [results,setResults,ready]=useStoredState('wc-blood-v2',[]);const[showHoldHint,setShowHoldHint]=useState(false);
 const [selectedKey,setSelectedKey]=useState('');
 const trends=useMemo(()=>buildBiomarkerTrends(results),[results]);const monthly=useMemo(()=>aggregateMonthly(results),[results]);const currentKey=new Date().toISOString().slice(0,7);const currentMonth=monthly.find(item=>item.month===currentKey);const latestDate=results.map(item=>item.date).filter(Boolean).sort().at(-1);
 const selectedIndex=Math.max(0,trends.findIndex(item=>item.biomarkerKey===selectedKey));const selectedTrend=trends[selectedIndex]||trends[0];
 const counts=trends.reduce((sum,item)=>{if(item.rangeStatus==='within-provided-range')sum.within+=1;else if(item.rangeStatus==='above-provided-range'||item.rangeStatus==='below-provided-range')sum.outside+=1;else sum.noRange+=1;if(item.change.direction!=='stable'&&item.change.direction!=='not-comparable')sum.changed+=1;return sum},{within:0,outside:0,noRange:0,changed:0});
 useEffect(()=>{setShowHoldHint(localStorage.getItem('wc-blood-long-press-used')!=='true')},[]);
 useEffect(()=>{if(trends.length&&!trends.some(item=>item.biomarkerKey===selectedKey))setSelectedKey(trends[0].biomarkerKey)},[trends,selectedKey]);
 useEffect(()=>{if(!ready)return;const cleaned=results.filter(row=>!isOldDemo(row)).map(ensureScanIdentity);if(cleaned.length!==results.length||cleaned.some((row,index)=>row.id!==results[index]?.id))setResults(cleaned)},[ready,results,setResults]);
 useEffect(()=>{if(ready)localStorage.setItem('wc-blood-monthly',JSON.stringify(monthly))},[ready,monthly]);
 return <div className="px-5 pb-5"><PageHeader title="Blood trends" backHref="/"/>
  {showHoldHint&&<div className="mb-1 flex items-center gap-2 rounded-xl border border-line bg-surface/70 px-3 py-2 text-xs text-inkSoft"><Icon name="info" size={16}/><p><strong className="text-ink">Hold the Blood icon below</strong> to open the Blood Scanner.</p></div>}
  <Card className="mt-4 border-0 bg-teal p-6 text-white"><p className="text-sm font-bold uppercase tracking-widest text-teal-light">Latest blood work</p><h2 className="mt-2 font-display text-3xl font-bold">{readableDate(latestDate)}</h2><p className="mt-2 text-sm text-white/75">{currentMonth?.scanCount||0} {(currentMonth?.scanCount||0)===1?'scan':'scans'} this month · {trends.length} {trends.length===1?'biomarker':'biomarkers'} tracked</p></Card>
  <Card className="mt-4 p-4"><div className="grid grid-cols-3 divide-x divide-line text-center"><div className="px-2"><strong className="font-display text-2xl text-teal-dark">{counts.within}</strong><p className="mt-1 text-sm leading-tight text-inkSoft">Within range</p></div><div className="px-2"><strong className="font-display text-2xl text-clay">{counts.outside}</strong><p className="mt-1 text-sm leading-tight text-inkSoft">Outside range</p></div><div className="px-2"><strong className="font-display text-2xl text-ink">{counts.noRange}</strong><p className="mt-1 text-sm leading-tight text-inkSoft">No range</p></div></div></Card>
  <div className="mb-3 mt-6 flex items-end justify-between"><div><p className="eyebrow">Individual results</p><h2 className="mt-1 font-display text-2xl font-bold">Biomarker trends</h2></div><span className="text-xs text-inkSoft">{counts.changed} changed</span></div>
  {selectedTrend?<><label className="block"><span className="label">Choose a biomarker</span><select className="field bg-surface" value={selectedTrend.biomarkerKey} onChange={event=>setSelectedKey(event.target.value)}>{trends.map(item=><option key={item.biomarkerKey} value={item.biomarkerKey}>{item.displayName} — {readableStatus(item.rangeStatus)}</option>)}</select></label>
   <div key={selectedTrend.biomarkerKey} className="step-enter-forward mt-3"><Card className="p-5"><div className="flex flex-col items-start gap-3 sm:flex-row sm:justify-between"><div className="min-w-0"><p className="text-sm font-bold text-teal-dark">{selectedIndex+1} of {trends.length}</p><h3 className="mt-1 font-display text-2xl font-bold">{selectedTrend.displayName}</h3></div><span className={`rounded-full px-3 py-1.5 text-sm font-bold ${statusTone(selectedTrend.rangeStatus)}`}>{readableStatus(selectedTrend.rangeStatus)}</span></div><p className="mt-3 text-sm leading-relaxed text-inkSoft">{explanations[selectedTrend.biomarkerKey]||'A result recorded from your laboratory report.'}</p><div className="mt-5 rounded-2xl bg-canvas p-4"><p className="text-sm text-inkSoft">Latest result</p><p className="mt-1"><strong className="font-display text-3xl">{selectedTrend.latest.value}</strong> <span className="text-base text-inkSoft">{selectedTrend.latest.unit||'unit not provided'}</span></p><p className="mt-2 font-bold">{changeText(selectedTrend)}</p></div><dl className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-line p-3"><dt className="text-sm text-inkSoft">Latest test</dt><dd className="mt-1 font-bold">{readableDate(selectedTrend.latest.testDate)}</dd></div><div className="rounded-xl border border-line p-3"><dt className="text-sm text-inkSoft">Printed range</dt><dd className="mt-1 font-bold">{selectedTrend.latest.range||'Not provided'}</dd></div><div className="rounded-xl border border-line p-3"><dt className="text-sm text-inkSoft">Previous comparable</dt><dd className="mt-1 font-bold">{selectedTrend.previous?`${selectedTrend.previous.value} ${selectedTrend.previous.unit}`:'Not available'}</dd></div><div className="rounded-xl border border-line p-3"><dt className="text-sm text-inkSoft">Percentage change</dt><dd className="mt-1 font-bold">{selectedTrend.change.percentage===null?'Not calculated':`${selectedTrend.change.percentage>0?'+':''}${selectedTrend.change.percentage.toFixed(1)}%`}</dd></div></dl>{selectedTrend.previous&&<p className="mt-4 text-sm leading-relaxed text-inkSoft">Compared with {readableDate(selectedTrend.previous.testDate)} using the same unit. An increase or decrease is not automatically better or worse.</p>}<p className="mt-2 text-sm text-inkSoft">{selectedTrend.resultCount} historical {selectedTrend.resultCount===1?'result':'results'} retained.</p></Card></div>
   <div className="mt-3 grid grid-cols-2 gap-3"><button type="button" className="min-h-touch rounded-2xl border border-line bg-surface px-3 font-bold text-teal-dark disabled:opacity-40" disabled={selectedIndex===0} onClick={()=>setSelectedKey(trends[selectedIndex-1].biomarkerKey)}><span aria-hidden="true">‹</span> Previous</button><button type="button" className="min-h-touch rounded-2xl border border-line bg-surface px-3 font-bold text-teal-dark disabled:opacity-40" disabled={selectedIndex===trends.length-1} onClick={()=>setSelectedKey(trends[selectedIndex+1].biomarkerKey)}>Next <span aria-hidden="true">›</span></button></div>
  </>:<Card><p className="text-center text-sm leading-relaxed text-inkSoft">No blood results yet. Hold the Blood icon to scan or enter a report.</p></Card>}
  {monthly.length>0&&<details className="mt-5 rounded-2xl border border-line bg-surface p-4"><summary className="cursor-pointer font-bold text-teal-dark">Monthly history ({monthly.length})</summary><div className="mt-4 space-y-3">{[...monthly].reverse().map(month=><div key={month.month} className="rounded-xl bg-canvas p-3"><div className="flex justify-between gap-3"><p className="font-bold">{new Date(`${month.month}-01T12:00`).toLocaleDateString('en-US',{month:'long',year:'numeric'})}</p><p className="text-xs text-inkSoft">{month.scanCount} {month.scanCount===1?'scan':'scans'}</p></div><p className="mt-1 text-xs text-inkSoft">{month.biomarkers.length} unit-compatible biomarker {month.biomarkers.length===1?'group':'groups'}; each calculated separately.</p></div>)}</div></details>}
  <p className="mt-5 text-center text-xs leading-relaxed text-inkSoft">Trends describe recorded changes and printed reference ranges. They do not rank biomarkers or interpret a change as medically better or worse.</p>
 </div>
}
