'use client';
import { useState } from 'react';
import PageHeader from '@/components/PageHeader';
import Card from '@/components/Card';
import BigButton from '@/components/BigButton';
import Modal from '@/components/Modal';
import Icon from '@/components/Icon';
import useStoredState from '@/components/useStoredState';
import { callAi, getAiSettings, readFileAsDataUrl, requestAiSetup } from '@/lib/aiClient';
import { extractTextLocally } from '@/lib/localOcr';
const seed=[{date:'2026-07-21',labs:[{name:'Hemoglobin',value:'12.4',unit:'g/dL'},{name:'White blood cells',value:'5.8',unit:'×10⁹/L'}]},{date:'2026-06-18',labs:[{name:'Hemoglobin',value:'12.1',unit:'g/dL'},{name:'White blood cells',value:'6.2',unit:'×10⁹/L'}]},{date:'2026-05-16',labs:[{name:'Hemoglobin',value:'12.6',unit:'g/dL'},{name:'White blood cells',value:'5.5',unit:'×10⁹/L'}]}];
function getValue(row,name){return Number((row.labs||[]).find(x=>x.name===name)?.value)}
function path(data,key){const vals=data.filter(x=>Number.isFinite(getValue(x,key))).slice(0,6).reverse();if(vals.length<2)return'';const nums=vals.map(x=>getValue(x,key));const min=Math.min(...nums)-.5,max=Math.max(...nums)+.5;return nums.map((v,i)=>`${i?'L':'M'} ${i*280/(nums.length-1)+10} ${130-(v-min)/(max-min)*100}`).join(' ')}
function MobileDateFields({ value, onChange }) {
 const [year,month,day]=value.split('-').map(Number);const now=new Date();const years=Array.from({length:11},(_,i)=>now.getFullYear()-10+i);const days=new Date(year,month,0).getDate();
 function set(part,next){const date={year,month,day};date[part]=Number(next);date.day=Math.min(date.day,new Date(date.year,date.month,0).getDate());onChange(`${date.year}-${String(date.month).padStart(2,'0')}-${String(date.day).padStart(2,'0')}`)}
 return <div><input type="hidden" name="date" value={value}/><div className="grid grid-cols-[1.35fr_.8fr_1fr] gap-2"><label><span className="label">Month</span><select className="field px-3" value={month} onChange={e=>set('month',e.target.value)}>{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{new Date(2000,i,1).toLocaleDateString('en-US',{month:'short'})}</option>)}</select></label><label><span className="label">Day</span><select className="field px-3" value={day} onChange={e=>set('day',e.target.value)}>{Array.from({length:days},(_,i)=><option key={i+1}>{i+1}</option>)}</select></label><label><span className="label">Year</span><select className="field px-3" value={year} onChange={e=>set('year',e.target.value)}>{years.map(item=><option key={item}>{item}</option>)}</select></label></div></div>
}
export default function BloodWork(){
 const [results,setResults]=useStoredState('wc-blood-v2',seed);const [open,setOpen]=useState(false);const [analysis,setAnalysis]=useState('');const [scanTexts,setScanTexts]=useState([]);const [scannedText,setScannedText]=useState('');const [scanProgress,setScanProgress]=useState(0);const [scanStage,setScanStage]=useState('');const [scanSaved,setScanSaved]=useState(0);const [analyzing,setAnalyzing]=useState(false);const [resultDate,setResultDate]=useState(()=>new Date().toISOString().slice(0,10));const latest=results[0]||seed[0];
 function add(e){e.preventDefault();const f=new FormData(e.currentTarget);const result={date:f.get('date'),labs:[{name:f.get('name'),value:f.get('value'),unit:f.get('unit'),range:f.get('range')} ]};setResults([result,...results].sort((a,b)=>b.date.localeCompare(a.date)));setOpen(false)}
 async function analyzeReport(e){const file=e.target.files[0];e.target.value='';if(!file)return;const settings=getAiSettings();if(!settings.profile||!settings.consent||!settings.config?.apiKey){requestAiSetup();return}setAnalyzing(true);setAnalysis('');setScanSaved(0);setScanProgress(0);setScanStage(`Reading photo ${scanTexts.length+1} of 3 on this device`);try{const optimizedImage=await readFileAsDataUrl(file);const text=await extractTextLocally(optimizedImage,setScanProgress);if(text.length<30)throw new Error('This photo did not contain enough readable text and was not counted. Try better lighting, hold the report flat, and fill the frame.');const next=[...scanTexts,text];setScanTexts(next);setScannedText(next.map((item,index)=>`SCAN ${index+1}\n${item}`).join('\n\n'));if(next.length<3){setAnalysis(`Photo ${next.length} of 3 was scanned locally. Take ${3-next.length} more ${3-next.length===1?'photo':'photos'} of the same report.`);return}setScanStage('Comparing three text scans');const response=await callAi({mode:'lab-consensus',ocrScans:next.map(item=>item.slice(0,8000)),profile:settings.profile,context:{recentLabs:results.slice(0,5)}});setAnalysis(response.text);if(response.labs?.length){const entry={date:response.reportDate||new Date().toISOString().slice(0,10),labs:response.labs,source:'3-photo OCR consensus'};setResults(current=>[entry,...current].sort((a,b)=>b.date.localeCompare(a.date)));setScanSaved(response.labs.length)}else{setAnalysis(`${response.text}\n\nThe three scans did not agree on enough information, so nothing was added to your blood-work log.`)}setScanTexts([])}catch(error){setAnalysis(error.message)}finally{setAnalyzing(false);setScanStage('')}}
 return <div className="px-5 pb-5"><PageHeader title="Blood work" backHref="/"/>
  <Card className="mt-4"><div className="flex items-start justify-between"><div><p className="eyebrow">Latest results</p><h2 className="mt-1 font-display text-2xl font-bold">Your trends</h2></div><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-clay-light text-clay"><Icon name="trend"/></span></div>
   <svg viewBox="0 0 300 145" className="mt-5 w-full" role="img" aria-label="Blood result trend chart"><path d="M10 30H290M10 80H290M10 130H290" stroke="#E4DACB" strokeWidth="1"/><path d={path(results,'Hemoglobin')} fill="none" stroke="#116466" strokeWidth="4" strokeLinecap="round"/><path d={path(results,'White blood cells')} fill="none" stroke="#B5563C" strokeWidth="4" strokeLinecap="round" strokeDasharray="3 7"/></svg>
   <div className="flex gap-4 text-xs font-bold"><span className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full bg-teal"/>Hemoglobin</span><span className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full bg-clay"/>White cells</span></div>
  </Card>
  <Card className="mt-4"><div className="flex justify-between"><h2 className="font-display text-xl font-bold">Most recent</h2><time className="text-sm text-inkSoft">{new Date(`${latest.date}T12:00`).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</time></div>
   <dl className="mt-4 grid grid-cols-2 gap-3">{latest.labs.map((lab,i)=><div key={`${lab.name}-${i}`} className={`rounded-2xl p-4 ${i%2?'bg-clay-light':'bg-teal-light'}`}><dt className="text-xs font-bold uppercase tracking-wide text-inkSoft">{lab.name}</dt><dd className={`mt-1 text-xl font-bold ${i%2?'text-clay':'text-teal-dark'}`}>{lab.value} <small className="text-xs">{lab.unit}</small></dd>{lab.range&&<p className="mt-1 text-xs text-inkSoft">Range: {lab.range}</p>}</div>)}</dl>
  </Card>
  <p className="mt-5 rounded-2xl bg-teal-light p-3 text-sm leading-relaxed text-teal-dark">For a reliable scan, take three photos of the same report. Keep the full page visible and slightly change the angle or distance each time.</p>
  <div className="mt-3 grid grid-cols-2 gap-3"><BigButton onClick={()=>setOpen(true)}><Icon name="plus"/>Enter value</BigButton><label className={`min-h-touch inline-flex cursor-pointer items-center justify-center gap-2 rounded-2xl border border-teal/40 bg-surface px-3 py-3 text-center text-sm font-bold text-teal-dark ${analyzing?'opacity-50':''}`}><Icon name="camera"/>{analyzing?'Scanning…':`Photo ${scanTexts.length+1} of 3`}<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" className="hidden" disabled={analyzing} onChange={analyzeReport}/></label></div>
  {scanTexts.length>0&&<div className="mt-3 flex items-center justify-between rounded-2xl bg-gold-light px-4 py-3"><p className="text-sm font-bold text-ink">{scanTexts.length} of 3 photos captured</p><button type="button" className="text-xs font-bold text-clay" onClick={()=>{setScanTexts([]);setScannedText('');setAnalysis('')}}>Start over</button></div>}
  {analyzing&&<Card className="mt-4"><div className="flex items-center gap-3"><span className="spinner h-7 w-7 shrink-0 rounded-full border-2 border-teal-light border-t-teal"/><div className="flex-1"><p className="text-sm font-bold">{scanStage}</p><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-line"><div className="h-full rounded-full bg-teal transition-all" style={{width:`${scanStage.startsWith('Explaining')?100:scanProgress}%`}}/></div><p className="mt-1 text-xs text-inkSoft">{scanStage.startsWith('Reading')?`${scanProgress}% · No AI tokens used yet`:'Sending text only · Report image stays on device'}</p></div></div></Card>}
  {analysis&&<Card className="mt-4 bg-teal-light"><div className="flex gap-3"><Icon name={scanTexts.length?'camera':'sparkle'} className="shrink-0 text-teal"/><div><h2 className="font-bold">{scanTexts.length?'Three-photo scan':'AI report explanation'}</h2>{scanSaved>0&&<p className="mt-2 flex items-center gap-2 rounded-xl bg-surface/80 p-3 text-sm font-bold text-teal-dark"><Icon name="check" size={18}/>{scanSaved} {scanSaved===1?'value':'values'} added to Blood Work</p>}<p className="mt-2 whitespace-pre-line text-sm leading-relaxed text-inkSoft">{analysis}</p>{!scanTexts.length&&<p className="mt-3 text-xs font-bold text-clay">Verify every saved value against the original report and your care team.</p>}</div></div></Card>}
  {scannedText&&<details className="mt-3 rounded-2xl border border-line bg-surface p-4"><summary className="cursor-pointer text-sm font-bold text-teal-dark">Review locally scanned text</summary><pre className="mt-3 max-h-48 overflow-auto whitespace-pre-wrap font-body text-xs leading-relaxed text-inkSoft">{scannedText}</pre></details>}
  <Modal open={open} title="Add any lab value" onClose={()=>setOpen(false)}><form className="mt-5 space-y-4" onSubmit={add}><fieldset><legend className="mb-3 font-bold">Test date</legend><MobileDateFields value={resultDate} onChange={setResultDate}/></fieldset><label className="block"><span className="label">Test name</span><input className="field" name="name" placeholder="Example: Platelets" required/></label><div className="grid grid-cols-2 gap-3"><label><span className="label">Value</span><input className="field" name="value" inputMode="decimal" required/></label><label><span className="label">Unit</span><input className="field" name="unit" placeholder="Example: g/dL"/></label></div><label className="block"><span className="label">Printed reference range</span><input className="field" name="range" placeholder="Optional"/></label><BigButton type="submit">Save result</BigButton></form></Modal>
 </div>
}
