'use client';
import { useEffect, useMemo, useState } from 'react';
import PageHeader from '@/components/PageHeader';
import Card from '@/components/Card';
import Icon from '@/components/Icon';
import useStoredState from '@/components/useStoredState';
import { buildBiomarkerTrends } from '@/lib/bloodTrends';

const explanations={hemoglobin:'A protein in red blood cells that carries oxygen.','white-blood-cells':'Cells involved in the body’s immune response.','red-blood-cells':'Cells that carry oxygen through the body.',platelets:'Blood components involved in clotting.',hematocrit:'The proportion of blood made up of red blood cells.',glucose:'The amount of sugar measured in the blood.',creatinine:'A waste product commonly measured in kidney-related testing.',sodium:'An electrolyte involved in fluid balance and nerve function.',potassium:'An electrolyte involved in muscle, nerve, and heart function.'};
function readableDate(date){return date?new Date(`${date}T12:00`).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'Not available'}
function readableStatus(status){return({'within-provided-range':'Within printed range','below-provided-range':'Below printed range','above-provided-range':'Above printed range','range-unavailable':'No range provided','range-unparseable':'Range could not be read','missing-value':'Value could not be read'}[status]||'Status unavailable')}
function statusTone(status){return status==='within-provided-range'?'bg-teal-light text-teal-dark':status==='below-provided-range'||status==='above-provided-range'?'bg-clay-light text-clay':'bg-gold-light text-ink'}
function changeText(trend){if(trend.comparisonStatus!=='comparable')return({'unit-mismatch':'Previous result uses a different unit','missing-unit':'A unit is needed for comparison','missing-value':'A numeric value is needed','not-enough-history':'No earlier compatible result'}[trend.comparisonStatus]||'Not comparable');const value=trend.change.absolute;return`${trend.change.direction[0].toUpperCase()+trend.change.direction.slice(1)} ${trend.change.direction==='stable'?'':`by ${Math.abs(Number(value.toFixed(2)))} ${trend.latest.unit}`}`.trim()}

export default function BiomarkerResults(){
 const[results]=useStoredState('wc-blood-v2',[]);const[selectedKey,setSelectedKey]=useState('');const trends=useMemo(()=>buildBiomarkerTrends(results),[results]);const selectedIndex=Math.max(0,trends.findIndex(item=>item.biomarkerKey===selectedKey));const trend=trends[selectedIndex]||trends[0];
 useEffect(()=>{if(trends.length&&!trends.some(item=>item.biomarkerKey===selectedKey))setSelectedKey(trends[0].biomarkerKey)},[trends,selectedKey]);
 return <div className="px-5 pb-5"><PageHeader title="Individual results" backHref="/blood-work"/>
  <p className="mt-2 text-sm leading-relaxed text-inkSoft">Choose one biomarker to review its latest value and comparison.</p>
  {trend?<><label className="mt-5 block"><span className="label">Choose a biomarker</span><select className="field bg-surface" value={trend.biomarkerKey} onChange={event=>setSelectedKey(event.target.value)}>{trends.map(item=><option key={item.biomarkerKey} value={item.biomarkerKey}>{item.displayName} — {readableStatus(item.rangeStatus)}</option>)}</select></label>
   <div key={trend.biomarkerKey} className="step-enter-forward mt-3"><Card><div className="flex flex-col items-start gap-3 sm:flex-row sm:justify-between"><div className="min-w-0"><p className="text-sm font-bold text-teal-dark">{selectedIndex+1} of {trends.length}</p><div className="mt-1 flex items-center gap-1"><button type="button" className="icon-button -ml-3 shrink-0 text-teal-dark disabled:opacity-30" aria-label="Show previous biomarker" disabled={selectedIndex===0} onClick={()=>setSelectedKey(trends[selectedIndex-1].biomarkerKey)}><Icon name="back" size={22}/></button><h2 className="min-w-0 font-display text-2xl font-bold">{trend.displayName}</h2><button type="button" className="icon-button shrink-0 text-teal-dark disabled:opacity-30" aria-label="Show next biomarker" disabled={selectedIndex===trends.length-1} onClick={()=>setSelectedKey(trends[selectedIndex+1].biomarkerKey)}><Icon name="chevron" size={22}/></button></div></div><span className={`rounded-full px-3 py-1.5 text-sm font-bold ${statusTone(trend.rangeStatus)}`}>{readableStatus(trend.rangeStatus)}</span></div><p className="mt-3 text-sm leading-relaxed text-inkSoft">{explanations[trend.biomarkerKey]||'A result recorded from your laboratory report.'}</p><div className="mt-5 rounded-2xl bg-canvas p-4"><p className="text-sm text-inkSoft">Latest result</p><p className="mt-1"><strong className="font-display text-3xl">{trend.latest.value}</strong> <span className="text-base text-inkSoft">{trend.latest.unit||'unit not provided'}</span></p><p className="mt-2 font-bold">{changeText(trend)}</p></div><dl className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-line p-3"><dt className="text-sm text-inkSoft">Latest test</dt><dd className="mt-1 font-bold">{readableDate(trend.latest.testDate)}</dd></div><div className="rounded-xl border border-line p-3"><dt className="text-sm text-inkSoft">Printed range</dt><dd className="mt-1 font-bold">{trend.latest.range||'Not provided'}</dd></div><div className="rounded-xl border border-line p-3"><dt className="text-sm text-inkSoft">Previous comparable</dt><dd className="mt-1 font-bold">{trend.previous?`${trend.previous.value} ${trend.previous.unit}`:'Not available'}</dd></div><div className="rounded-xl border border-line p-3"><dt className="text-sm text-inkSoft">Percentage change</dt><dd className="mt-1 font-bold">{trend.change.percentage===null?'Not calculated':`${trend.change.percentage>0?'+':''}${trend.change.percentage.toFixed(1)}%`}</dd></div></dl>{trend.previous&&<p className="mt-4 text-sm leading-relaxed text-inkSoft">Compared with {readableDate(trend.previous.testDate)} using the same unit. An increase or decrease is not automatically better or worse.</p>}<p className="mt-2 text-sm text-inkSoft">{trend.resultCount} historical {trend.resultCount===1?'result':'results'} retained.</p></Card></div>
  </>:<Card className="mt-5"><p className="text-center text-sm text-inkSoft">No individual blood results are available yet.</p></Card>}
  <p className="mt-5 text-center text-xs leading-relaxed text-inkSoft">Changes are descriptive and do not automatically mean medically better or worse.</p>
 </div>
}
