export const DEFAULT_STABILITY_TOLERANCE_PERCENT=1;

const definitions=[
 {key:'hemoglobin',displayName:'Hemoglobin',aliases:['hemoglobin','haemoglobin','hgb','hb'],category:'CBC'},
 {key:'white-blood-cells',displayName:'White blood cells',aliases:['white blood cells','white blood cell','wbc','leukocytes'],category:'CBC'},
 {key:'red-blood-cells',displayName:'Red blood cells',aliases:['red blood cells','red blood cell','rbc','erythrocytes'],category:'CBC'},
 {key:'platelets',displayName:'Platelets',aliases:['platelets','platelet count','plt'],category:'CBC'},
 {key:'hematocrit',displayName:'Hematocrit',aliases:['hematocrit','haematocrit','hct'],category:'CBC'},
 {key:'glucose',displayName:'Glucose',aliases:['glucose','blood glucose'],category:'Metabolic'},
 {key:'creatinine',displayName:'Creatinine',aliases:['creatinine'],category:'Kidney'},
 {key:'sodium',displayName:'Sodium',aliases:['sodium','na'],category:'Electrolytes'},
 {key:'potassium',displayName:'Potassium',aliases:['potassium','k'],category:'Electrolytes'},
];
const aliasMap=new Map(definitions.flatMap(item=>item.aliases.map(alias=>[alias,item])));
function cleanName(value){return String(value||'').trim().toLowerCase().replace(/[._]/g,' ').replace(/\s+/g,' ')}
export function normalizeBiomarker(name){const clean=cleanName(name);const known=aliasMap.get(clean);return known||{key:clean.replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'unknown',displayName:String(name||'Unknown biomarker').trim()||'Unknown biomarker',aliases:[clean],category:'Other'}}
export function normalizeUnit(unit){return String(unit||'').trim().toLowerCase().replace(/\s+/g,'').replace(/μ/g,'µ')}
export function numericValue(value){const match=String(value??'').replace(',','.').match(/-?\d+(?:\.\d+)?/);return match?Number(match[0]):null}
export function parseReferenceRange(range){const text=String(range||'').trim().replace(/[–—]/g,'-').replace(/,/g,'.');if(!text)return null;const threshold=text.match(/-?\d+(?:\.\d+)?/);if(/^(?:<|≤|up to|less than)/i.test(text)&&threshold)return{max:Number(threshold[0])};if(/^(?:>|≥|at least|more than)/i.test(text)&&threshold)return{min:Number(threshold[0])};const bounded=text.match(/^(-?\d+(?:\.\d+)?)\s*-\s*(-?\d+(?:\.\d+)?)$/);if(bounded){const a=Number(bounded[1]),b=Number(bounded[2]);return{min:Math.min(a,b),max:Math.max(a,b)}}return null}
export function rangeStatus(lab){const value=numericValue(lab.value);if(!Number.isFinite(value))return'missing-value';if(!String(lab.range||'').trim())return'range-unavailable';const range=parseReferenceRange(lab.range);if(!range)return'range-unparseable';if(range.min!==undefined&&value<range.min)return'below-provided-range';if(range.max!==undefined&&value>range.max)return'above-provided-range';return'within-provided-range'}
function normalizedLab(lab){const biomarker=normalizeBiomarker(lab.name);return[biomarker.key,String(lab.value||'').trim().toLowerCase().replace(/\s+/g,''),normalizeUnit(lab.unit),String(lab.range||'').trim().toLowerCase().replace(/[\s,–—]+/g,'')].join('|')}
function stableHash(value){let hash=2166136261;for(let index=0;index<value.length;index+=1){hash^=value.charCodeAt(index);hash=Math.imul(hash,16777619)}return(hash>>>0).toString(36)}
export function scanFingerprint(scan,sourceText=''){const labs=(scan.labs||[]).map(normalizedLab).sort().join('||');const source=String(sourceText).toLowerCase().replace(/[\s.,;:]+/g,'').trim();return`scan-${stableHash(`${scan.date||''}::${labs}::${source}`)}`}
export function ensureScanIdentity(scan){return{...scan,id:scan.id||scanFingerprint(scan),createdAt:scan.createdAt||`${scan.date||new Date().toISOString().slice(0,10)}T12:00:00.000Z`}}
function validDate(value){return/^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(new Date(`${value}T12:00`).getTime())}
function overlapRatio(a,b){const first=new Map((a.labs||[]).map(lab=>[`${normalizeBiomarker(lab.name).key}|${normalizeUnit(lab.unit)}`,numericValue(lab.value)]));const second=new Map((b.labs||[]).map(lab=>[`${normalizeBiomarker(lab.name).key}|${normalizeUnit(lab.unit)}`,numericValue(lab.value)]));if(!first.size||!second.size)return 0;let matches=0;first.forEach((value,key)=>{const other=second.get(key);if(Number.isFinite(value)&&Number.isFinite(other)&&Math.abs(value-other)<=Math.max(Math.abs(value),1)*.005)matches+=1});return matches/Math.max(first.size,second.size)}
export function classifyDuplicate(candidate,existing){if(existing.some(scan=>scanFingerprint(scan)===scanFingerprint(candidate)))return{status:'exact-duplicate'};const similar=existing.find(scan=>scan.date===candidate.date&&overlapRatio(scan,candidate)>=.7);return similar?{status:'possible-duplicate',matchingScanId:similar.id,similarity:overlapRatio(similar,candidate)}:{status:'unique'}}
function uniqueScans(scans){const seen=new Set();return scans.map(ensureScanIdentity).filter(scan=>{const fingerprint=scanFingerprint(scan);if(seen.has(fingerprint))return false;seen.add(fingerprint);return true})}
function entriesFrom(scans){return uniqueScans(scans).flatMap(scan=>(scan.labs||[]).map((lab,index)=>{const biomarker=normalizeBiomarker(lab.name);return{...lab,biomarkerKey:biomarker.key,displayName:biomarker.displayName,category:biomarker.category,numericValue:numericValue(lab.value),normalizedUnit:normalizeUnit(lab.unit),testDate:scan.date,scanId:scan.id,index,rangeStatus:rangeStatus(lab)}})).filter(item=>validDate(item.testDate)).sort((a,b)=>b.testDate.localeCompare(a.testDate)||b.index-a.index)}
export function buildBiomarkerTrends(scans,{tolerancePercent=DEFAULT_STABILITY_TOLERANCE_PERCENT}={}){const grouped=new Map();entriesFrom(scans).forEach(entry=>{if(!grouped.has(entry.biomarkerKey))grouped.set(entry.biomarkerKey,[]);grouped.get(entry.biomarkerKey).push(entry)});return[...grouped.values()].map(entries=>{const latest=entries[0];let comparisonStatus='comparable';let previous=null;if(!Number.isFinite(latest.numericValue))comparisonStatus='missing-value';else if(!latest.normalizedUnit)comparisonStatus='missing-unit';else{previous=entries.slice(1).find(item=>item.normalizedUnit===latest.normalizedUnit&&Number.isFinite(item.numericValue))||null;if(!previous){const hasOtherUnit=entries.slice(1).some(item=>item.normalizedUnit&&item.normalizedUnit!==latest.normalizedUnit);comparisonStatus=hasOtherUnit?'unit-mismatch':'not-enough-history'}}let absolute=null,percentage=null,direction='not-comparable';if(comparisonStatus==='comparable'&&previous){absolute=latest.numericValue-previous.numericValue;if(Math.abs(previous.numericValue)>1e-9)percentage=absolute/Math.abs(previous.numericValue)*100;const percentMagnitude=percentage===null?Infinity:Math.abs(percentage);direction=percentMagnitude<=tolerancePercent?'stable':absolute>0?'increased':absolute<0?'decreased':'stable'}return{biomarkerKey:latest.biomarkerKey,displayName:latest.displayName,category:latest.category,latest,previous,change:{absolute,percentage:Number.isFinite(percentage)?percentage:null,direction},rangeStatus:latest.rangeStatus,comparisonStatus,resultCount:entries.length,history:entries}}).sort((a,b)=>a.displayName.localeCompare(b.displayName))}
export function aggregateMonthly(scans){const clean=uniqueScans(scans);const months=new Map();clean.forEach(scan=>{if(!validDate(scan.date))return;const month=scan.date.slice(0,7);if(!months.has(month))months.set(month,{month,scans:[],entries:[]});const group=months.get(month);group.scans.push(scan);(scan.labs||[]).forEach(lab=>{const biomarker=normalizeBiomarker(lab.name);const value=numericValue(lab.value);group.entries.push({...lab,biomarkerKey:biomarker.key,displayName:biomarker.displayName,numericValue:value,normalizedUnit:normalizeUnit(lab.unit),testDate:scan.date,rangeStatus:rangeStatus(lab)})})});const ordered=[...months.values()].sort((a,b)=>a.month.localeCompare(b.month));return ordered.map((group,index)=>{const biomarkers=new Map();group.entries.filter(item=>Number.isFinite(item.numericValue)).forEach(item=>{const key=`${item.biomarkerKey}|${item.normalizedUnit||'missing-unit'}`;if(!biomarkers.has(key))biomarkers.set(key,{biomarkerKey:item.biomarkerKey,displayName:item.displayName,unit:item.unit||'',normalizedUnit:item.normalizedUnit,results:[]});biomarkers.get(key).results.push(item)});return{month:group.month,scanCount:group.scans.length,scanIds:group.scans.map(scan=>scan.id),biomarkers:[...biomarkers.values()].map(item=>{const values=item.results.map(result=>result.numericValue);const latest=item.results.sort((a,b)=>b.testDate.localeCompare(a.testDate))[0];const previousMonth=[...ordered.slice(0,index)].reverse().flatMap(old=>old.entries).filter(entry=>entry.biomarkerKey===item.biomarkerKey&&entry.normalizedUnit===item.normalizedUnit&&Number.isFinite(entry.numericValue));const prior=previousMonth.filter(entry=>entry.testDate.slice(0,7)===ordered.slice(0,index).reverse().find(old=>old.entries.some(entry=>entry.biomarkerKey===item.biomarkerKey&&entry.normalizedUnit===item.normalizedUnit))?.month);const priorAverage=prior.length?prior.reduce((sum,result)=>sum+result.numericValue,0)/prior.length:null;const average=values.reduce((sum,value)=>sum+value,0)/values.length;const change=Number.isFinite(priorAverage)?average-priorAverage:null;return{biomarkerKey:item.biomarkerKey,displayName:item.displayName,resultCount:values.length,latestValue:latest.numericValue,latestDate:latest.testDate,averageValue:average,minimumValue:Math.min(...values),maximumValue:Math.max(...values),unit:item.unit,previousMonthAverage:priorAverage,changeFromPreviousMonth:change,direction:change===null?'not-comparable':Math.abs(change/Math.max(Math.abs(priorAverage),1)*100)<=DEFAULT_STABILITY_TOLERANCE_PERCENT?'stable':change>0?'increased':'decreased'}}).sort((a,b)=>a.displayName.localeCompare(b.displayName)),updatedAt:new Date().toISOString()}})}
