'use client';
import { useState } from 'react';
import PageHeader from '@/components/PageHeader';
import Card from '@/components/Card';
import BigButton from '@/components/BigButton';
import Modal from '@/components/Modal';
import Icon from '@/components/Icon';
import MobileDateFields from '@/components/MobileDateFields';
import useStoredState from '@/components/useStoredState';
import { callAi, getAiSettings, readFileAsDataUrl, requestAiSetup } from '@/lib/aiClient';
import { extractTextLocally } from '@/lib/localOcr';
import { classifyDuplicate, ensureScanIdentity, scanFingerprint } from '@/lib/bloodTrends';

export default function BloodScanner(){
 const [results,setResults]=useStoredState('wc-blood-v2',[]);
 const [photos,setPhotos]=useState([]);const [progress,setProgress]=useState(0);const [stage,setStage]=useState('');const [message,setMessage]=useState('');const [processing,setProcessing]=useState(false);const [pending,setPending]=useState(null);const [notice,setNotice]=useState('');const [open,setOpen]=useState(false);const [editing,setEditing]=useState(null);const [resultDate,setResultDate]=useState(()=>new Date().toISOString().slice(0,10));
 function resetScanner(){setPhotos([]);setPending(null);setMessage('');setNotice('');setProgress(0);setStage('')}
 async function processPhoto(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;const settings=getAiSettings();if(!settings.profile||!settings.consent||!settings.config?.apiKey){requestAiSetup();return}setProcessing(true);setMessage('');setNotice('');setPending(null);setProgress(0);setStage(`Reading photo ${photos.length+1} of 3 on this device`);try{const image=await readFileAsDataUrl(file);const text=await extractTextLocally(image,setProgress);if(text.length<30)throw new Error('Not enough readable text was found. Try better lighting, hold the report flat, and fill the frame.');const next=[...photos,{image,text,name:file.name}].slice(0,3);setPhotos(next);if(next.length<3){setMessage(`Photo ${next.length} is ready. Take ${3-next.length} more ${3-next.length===1?'photo':'photos'} of the same report.`);return}setStage('Comparing the three local text scans');const response=await callAi({mode:'lab-consensus',ocrScans:next.map(item=>item.text.slice(0,8000)),profile:settings.profile,context:{recentLabs:results.slice(0,5)}});if(response.labs?.length){setPending({date:response.reportDate||new Date().toISOString().slice(0,10),labs:response.labs,summary:response.text,source:'3-photo OCR consensus'});setMessage('Review the extracted results below. Nothing is saved until you confirm.')}else setMessage(`${response.text}\n\nThe scans did not agree on enough information. Nothing was saved.`)}catch(error){setMessage(error.message)}finally{setProcessing(false);setStage('')}}
 function acceptEntry(entry){const duplicate=classifyDuplicate(entry,results);if(duplicate.status==='exact-duplicate'){setNotice('This exact report is already in your history. It was not saved again.');return false}if(duplicate.status==='possible-duplicate'&&!window.confirm('A very similar report from the same date is already saved. Keep this as a separate result?')){setNotice('The possible duplicate was discarded.');return false}setResults(current=>[entry,...current].sort((a,b)=>b.date.localeCompare(a.date)));return true}
 function savePending(){const entry=ensureScanIdentity({...pending,createdAt:new Date().toISOString()});if(acceptEntry(entry))setNotice(`${entry.labs.length} ${entry.labs.length===1?'value':'values'} saved. Your individual Blood Trends were updated.`);setPending(null);setPhotos([])}
 function addManual(e){e.preventDefault();const f=new FormData(e.currentTarget);const entry=ensureScanIdentity({date:f.get('date'),createdAt:new Date().toISOString(),source:'Manual entry',labs:[{name:f.get('name'),value:f.get('value'),unit:f.get('unit'),range:f.get('range')}]});if(acceptEntry(entry))setNotice('Result saved. Your individual Blood Trends were updated.');setOpen(false)}
 function remove(id){if(window.confirm('Delete this scan? Monthly Blood Trends will be recalculated.'))setResults(current=>current.filter(item=>item.id!==id))}
 function updateLab(index,key,value){setEditing(scan=>({...scan,labs:scan.labs.map((lab,i)=>i===index?{...lab,[key]:value}:lab)}))}
 function saveEdit(e){e.preventDefault();const revised={...editing,id:scanFingerprint(editing)};const others=results.filter(item=>item.id!==editing.id);const duplicate=classifyDuplicate(revised,others);if(duplicate.status==='exact-duplicate')setNotice('Those corrections match an existing scan, so they were not saved.');else if(duplicate.status==='possible-duplicate'&&!window.confirm('These corrections closely match another result from the same date. Keep both?'))setNotice('The possible duplicate correction was discarded.');else{setResults(current=>current.map(item=>item.id===editing.id?revised:item).sort((a,b)=>b.date.localeCompare(a.date)));setNotice('Scan corrected. Individual Blood Trends were recalculated.')}setEditing(null)}
 return <div className="scanner-enter px-5 pb-5"><PageHeader title="Blood Scanner" backHref="/blood-work"/>
  <Card className="mt-4 overflow-hidden border-0 bg-teal p-0 text-white"><div className="p-6"><p className="text-sm font-bold uppercase tracking-widest text-teal-light">Three-photo check</p><h2 className="mt-1 font-display text-2xl font-bold">Scan one lab report</h2><p className="mt-2 text-sm leading-relaxed text-white/75">Photograph the same report three times. Text is read locally, then the three readings are compared.</p></div><div className="grid grid-cols-3 border-t border-white/15">{[0,1,2].map(index=><div key={index} className={`flex h-12 items-center justify-center gap-2 border-r border-white/15 last:border-0 ${photos[index]?'bg-white/15':''}`}><Icon name={photos[index]?'check':'camera'} size={18}/><span className="text-xs font-bold">{index+1}</span></div>)}</div></Card>
  <div className="mt-4 grid grid-cols-2 gap-3"><label className={`min-h-touch inline-flex cursor-pointer items-center justify-center gap-2 rounded-2xl bg-teal px-3 py-3 text-center text-sm font-bold text-white ${processing||photos.length===3?'pointer-events-none opacity-50':''}`}><Icon name="camera"/>{processing?'Reading…':'Use camera'}<input type="file" accept="image/*" capture="environment" className="hidden" disabled={processing||photos.length===3} onChange={processPhoto}/></label><label className={`min-h-touch inline-flex cursor-pointer items-center justify-center gap-2 rounded-2xl border border-teal/40 bg-surface px-3 py-3 text-center text-sm font-bold text-teal-dark ${processing||photos.length===3?'pointer-events-none opacity-50':''}`}><Icon name="upload"/>Upload image<input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" disabled={processing||photos.length===3} onChange={processPhoto}/></label></div>
  <button type="button" className="mt-3 w-full text-sm font-bold text-teal-dark" onClick={()=>setOpen(true)}>Or enter a result manually</button>
  {photos.length>0&&<Card className="mt-4"><div className="flex items-center justify-between"><h2 className="font-display text-xl font-bold">Image preview</h2><button type="button" className="text-xs font-bold text-clay" onClick={resetScanner}>Rescan all</button></div><div className="mt-3 grid grid-cols-3 gap-2">{photos.map((photo,index)=><div key={index} className="overflow-hidden rounded-xl bg-canvas"><img src={photo.image} alt={`Lab report capture ${index+1}`} className="aspect-[3/4] w-full object-cover"/><p className="py-1 text-center text-[11px] font-bold text-inkSoft">Photo {index+1}</p></div>)}</div></Card>}
  {processing&&<Card className="mt-4"><div className="flex items-center gap-3"><span className="spinner h-7 w-7 shrink-0 rounded-full border-2 border-teal-light border-t-teal"/><div className="flex-1"><p className="text-sm font-bold">{stage}</p><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-line"><div className="h-full rounded-full bg-teal transition-all" style={{width:`${stage.startsWith('Reading')?progress:100}%`}}/></div><p className="mt-1 text-xs text-inkSoft">{stage.startsWith('Reading')?`${progress}% · local OCR uses no AI tokens`:'Only extracted text is sent for comparison'}</p></div></div></Card>}
  {message&&<p className="mt-4 whitespace-pre-line rounded-2xl bg-teal-light p-4 text-sm leading-relaxed text-teal-dark">{message}</p>}
  {pending&&<Card className="mt-4"><div className="flex items-start gap-3"><Icon name="clipboard" className="mt-1 shrink-0 text-teal-dark"/><div><p className="eyebrow">Ready to confirm</p><h2 className="mt-1 font-display text-xl font-bold">{pending.labs.length} extracted {pending.labs.length===1?'value':'values'}</h2></div></div><div className="mt-4 space-y-2">{pending.labs.map((lab,index)=><div key={`${lab.name}-${index}`} className="rounded-xl bg-canvas p-3"><p className="font-bold">{lab.name}</p><p className="mt-1 text-sm text-inkSoft">{lab.value} {lab.unit} {lab.range&&`· range ${lab.range}`}</p></div>)}</div><p className="mt-4 text-sm leading-relaxed text-inkSoft">{pending.summary}</p><div className="mt-4 grid grid-cols-2 gap-3"><button type="button" className="min-h-touch rounded-2xl border border-line font-bold text-clay" onClick={resetScanner}>Rescan</button><BigButton onClick={savePending}><Icon name="check"/>Confirm & save</BigButton></div></Card>}
  {notice&&<p className="mt-4 rounded-2xl bg-gold-light p-4 text-sm font-bold text-ink">{notice}</p>}
  {results.length>0&&<details className="mt-5 rounded-2xl border border-line bg-surface p-4"><summary className="cursor-pointer font-bold text-teal-dark">Scan history ({results.length})</summary><div className="mt-4 space-y-3">{results.map(scan=><div key={scan.id} className="rounded-2xl bg-canvas p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{new Date(`${scan.date}T12:00`).toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}</p><p className="mt-1 text-xs text-inkSoft">{scan.source||'Saved result'} · {scan.labs?.length||0} values</p></div><div className="flex gap-3"><button type="button" className="text-xs font-bold text-teal-dark" onClick={()=>setEditing(JSON.parse(JSON.stringify(scan)))}>Edit</button><button type="button" className="text-xs font-bold text-clay" onClick={()=>remove(scan.id)}>Delete</button></div></div><p className="mt-3 text-sm text-inkSoft">{scan.labs?.map(lab=>`${lab.name}: ${lab.value} ${lab.unit||''}`).join(' · ')}</p></div>)}</div></details>}
  <Modal open={open} title="Add any lab value" onClose={()=>setOpen(false)}><form className="mt-5 space-y-4" onSubmit={addManual}><fieldset><legend className="mb-3 font-bold">Test date</legend><MobileDateFields value={resultDate} onChange={setResultDate}/></fieldset><label className="block"><span className="label">Test name</span><input className="field" name="name" required/></label><div className="grid grid-cols-2 gap-3"><label><span className="label">Value</span><input className="field" name="value" inputMode="decimal" required/></label><label><span className="label">Unit</span><input className="field" name="unit"/></label></div><label className="block"><span className="label">Printed reference range</span><input className="field" name="range"/></label><BigButton type="submit">Save result</BigButton></form></Modal>
  <Modal open={!!editing} title="Correct saved scan" onClose={()=>setEditing(null)}>{editing&&<form className="mt-5 space-y-4" onSubmit={saveEdit}><MobileDateFields value={editing.date} onChange={date=>setEditing({...editing,date})}/>{editing.labs.map((lab,index)=><div key={index} className="space-y-3 rounded-2xl border border-line bg-canvas p-4"><label><span className="label">Test name</span><input className="field" value={lab.name} onChange={e=>updateLab(index,'name',e.target.value)} required/></label><div className="grid grid-cols-2 gap-3"><label><span className="label">Value</span><input className="field" value={lab.value} onChange={e=>updateLab(index,'value',e.target.value)} required/></label><label><span className="label">Unit</span><input className="field" value={lab.unit||''} onChange={e=>updateLab(index,'unit',e.target.value)}/></label></div><label><span className="label">Reference range</span><input className="field" value={lab.range||''} onChange={e=>updateLab(index,'range',e.target.value)}/></label></div>)}<BigButton type="submit">Save corrections</BigButton></form>}</Modal>
 </div>
}
